// Fonte oficial: FIFA/Coca-Cola Men's World Ranking.
// Estes dados foram gerados em 2026-06-09 a partir do endpoint oficial
// `https://api.fifa.com/api/v3/fifarankings/rankings/live?gender=1&sportType=0&language=en`,
// usando `PrevRank` como a edicao oficial mais recente publicada em 2026-04-01.
export const TEAM_FIFA_RANKINGS = {
  'México': { code: 'MEX', officialRank: 15 },
  'África do Sul': { code: 'RSA', officialRank: 60 },
  'Coreia do Sul': { code: 'KOR', officialRank: 25 },
  'Rep. Tcheca': { code: 'CZE', officialRank: 41 },
  'Canadá': { code: 'CAN', officialRank: 30 },
  'Bósnia': { code: 'BIH', officialRank: 65 },
  'Catar': { code: 'QAT', officialRank: 55 },
  'Suíça': { code: 'SUI', officialRank: 19 },
  'Brasil': { code: 'BRA', officialRank: 6 },
  'Marrocos': { code: 'MAR', officialRank: 8 },
  'Haiti': { code: 'HAI', officialRank: 83 },
  'Escócia': { code: 'SCO', officialRank: 43 },
  'EUA': { code: 'USA', officialRank: 16 },
  'Paraguai': { code: 'PAR', officialRank: 40 },
  'Austrália': { code: 'AUS', officialRank: 27 },
  'Turquia': { code: 'TUR', officialRank: 22 },
  'Alemanha': { code: 'GER', officialRank: 10 },
  'Costa do Marfim': { code: 'CIV', officialRank: 34 },
  'Curaçao': { code: 'CUW', officialRank: 82 },
  'Equador': { code: 'ECU', officialRank: 23 },
  'Holanda': { code: 'NED', officialRank: 7 },
  'Japão': { code: 'JPN', officialRank: 18 },
  'Suécia': { code: 'SWE', officialRank: 38 },
  'Tunísia': { code: 'TUN', officialRank: 44 },
  'Bélgica': { code: 'BEL', officialRank: 9 },
  'Egito': { code: 'EGY', officialRank: 29 },
  'Irã': { code: 'IRN', officialRank: 21 },
  'Nova Zelândia': { code: 'NZL', officialRank: 85 },
  'Espanha': { code: 'ESP', officialRank: 2 },
  'Cabo Verde': { code: 'CPV', officialRank: 69 },
  'Arábia Saudita': { code: 'KSA', officialRank: 61 },
  'Uruguai': { code: 'URU', officialRank: 17 },
  'França': { code: 'FRA', officialRank: 1 },
  'Senegal': { code: 'SEN', officialRank: 14 },
  'Iraque': { code: 'IRQ', officialRank: 57 },
  'Noruega': { code: 'NOR', officialRank: 31 },
  'Argentina': { code: 'ARG', officialRank: 3 },
  'Argélia': { code: 'ALG', officialRank: 28 },
  'Áustria': { code: 'AUT', officialRank: 24 },
  'Jordânia': { code: 'JOR', officialRank: 63 },
  'Portugal': { code: 'POR', officialRank: 5 },
  'RD Congo': { code: 'COD', officialRank: 46 },
  'Uzbequistão': { code: 'UZB', officialRank: 50 },
  'Colômbia': { code: 'COL', officialRank: 13 },
  'Inglaterra': { code: 'ENG', officialRank: 4 },
  'Croácia': { code: 'CRO', officialRank: 11 },
  'Gana': { code: 'GHA', officialRank: 74 },
  'Panamá': { code: 'PAN', officialRank: 33 }
};
