name = "bolao2026-avatar-upload"
main = "avatar-upload-worker.js"
compatibility_date = "2026-06-10"
account_id = "e8617b066fa6d5275555be09fd366d52"

[[r2_buckets]]
binding = "AVATARS_BUCKET"
bucket_name = "bolao2026-avatars"

[vars]
ALLOWED_ORIGINS = "https://lhgcampos.github.io,http://localhost:5174,http://127.0.0.1:4175,http://127.0.0.1:4174,http://localhost:4175"
PUBLIC_AVATAR_BASE_URL = "https://pub-56fbf4716fdc4ab69e70b4c56f28fccf.r2.dev"
